### ISSUE TITLE
Default Locale Not Set - Probably Spring 5 (webflux) issue?

### ISSUE THREAD

**Issue by dharrigan** [thymeleaf/thymeleaf-spring#144] opened 2017-06-26 15:33 UTC
Hi Daniel,

Discovered this issue with Spring 5 (RC2) with spring-boot-starter-webflux and Thymeleaf 3 (Spring 5 - 3.07-SNAPSHOT). It appears that the default locale is not being set and thus causes Thymeleaf to raise an exception. I'm happy to provide the sample project if required (it's very small and just a controller class referencing a template)

Original Issue raised on Spring Boot: https://github.com/spring-projects/spring-boot/issues/9588
Now also on Spring Jira: https://jira.spring.io/browse/SPR-15705

Sample project:

https://github.com/dharrigan/SPR-15705

Please let me know if I can be of further assistance.

-=david=-

**Comment by danielfernandez** [comment] 2017-07-08 00:51
Thanks for the report.

Your sample project gives me errors when executing `gradle`. First because it doesn't include the location of the *milestone* and *snapshot* Spring maven/gradle repositories (needed to download the Gradle Boot plugin). But when I add them to `build.properties`, I get:

```
➜  SPR-15705 git:(master) ✗ gradle bootRun
:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not find org.springframework.boot:spring-boot-starter-webflux:.
  Searched in the following locations:
      https://oss.sonatype.org/content/repositories/snapshots/org/springframework/boot/spring-boot-starter-webflux//spring-boot-starter-webflux-.pom
      https://oss.sonatype.org/content/repositories/snapshots/org/springframework/boot/spring-boot-starter-webflux//spring-boot-starter-webflux-.jar
      https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-webflux//spring-boot-starter-webflux-.pom
      https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-starter-webflux//spring-boot-starter-webflux-.jar
  Required by:
      project :
> Could not find org.springframework.boot:spring-boot-starter-thymeleaf:.
  Required by:
      project :
> Could not find org.springframework.security:spring-security-web:5.0.0.M2.
  Required by:
      project :
> Could not find io.projectreactor:reactor-core:.
  Required by:
      project :
> Could not find io.projectreactor:reactor-kotlin-extensions:1.0.0.M2.
  Required by:
      project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Anyway, I've tried with one of Thymeleaf's own sandbox applications, setting Spring Boot to `2.0.0.M2` and I'm able to reproduce the issue, but not with `2.0.0.BUILD-SNAPSHOT` (with this version it works alright).

I see you opened a ticket on Spring's JIRA --which for some reason I was not getting notifications for :(--, so I'll first continue the discussion there in order to be sure about whether they plan to actually make `null` locales possible at `View` implementations or not…

**Comment by danielfernandez** [comment] 2017-07-19 22:51
Closing after SPR-15705 has been closed too.

**Closed as completed by danielfernandez** 2017-07-19 22:51 UTC
Labels: tracker:question, status:answered

**Comment by dharrigan** [comment] 2017-07-20 07:25
Thank you! :-)
